from ditto.shape_generator import polygon_generator
import numpy as np


Config = {'img_size':(1024, 1280),
          'radius_range': (50, 51),
          'uncentral_range' : ((60, 61), (60, 61)),
          'source_light_pos':(0,0,1000000),
          'ref_light_height':1000000,
          'ref_light_offset': np.sqrt(1280000 ** 2 + 2000000**2),
          'ref_light_angle': (-np.pi/2, 0),
          # 'ref_light_angle': np.arctan(-2000000/1280000),
          'first_phase': (-0.5 * np.pi, 0.5 * np.pi),
          'frequency':(1.160, 1.2),#1.180
          'suffle': True,
          'smooth':10,
          'draw_over': False,
          'with_abberation': False,
          'normalize': True,
          'binary':True,
          # 'tilt_abberation': {'slop_direction':(0,1),
          #                     'slop':0.01,
          #                     'lowest_height': 0},
          # 'Square':{'radius_range': (0.3, 0.3),
          #             'num_range': (2, 4),
          #             'num_point_range':(4, 6),
          #             'height_range': (3.5, 5.0),
          #             'random_rotate': True},
          'Ellipse':{'radius_range':(0.1, 0.2),
                     'long_axis_range':(1.0, 1.1),
                     'short_axis_range': (0.9, 1.0),
                     'num_range':(4, 5),
                     'height_range':(3.5, 5.0),
                     'random_rotate':True
                    },
          # 'Polygon': {'radius_range': (0.2, 0.2),
          #             'num_range': (4, 5),
          #             'num_point_range':(3, 4),
          #             'height_range': (3.5, 5),
          #             'random_rotate': True,
          #             'irregular': True},
          }